title:  Blog
author:  Zoe Braiterman
description:  Technical / Security Content
twitter_username:  zbraiterman
github_username:  zbraiterman
url:  zbraiterman.github.io

# Build settings
theme: jekyll-theme-cayman
