# Site settings
title:  Blog
author:  Zoe Braiterman
description:  Technical / Security Content 
twitter_username:  zbraiterman
github_username:  zbraiterman

# Build settings
markdown:  kramdown
theme:  minima


